spring:
  application:
    name: microservice-produits

  datasource:
    url: jdbc:h2:mem:product-db
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 9001

# Configuration personnalisée
mes-configs:
  limitDeProduits: 4
